### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [pyamsoft/tetherfi#307]
The scanner here reported for your last release:

```
! repo/com.pyamsoft.tetherfi_41.apk declares sensitive permission(s):
  android.permission.ACCESS_FINE_LOCATION
  android.permission.ACCESS_COARSE_LOCATION
  android.permission.NEARBY_WIFI_DEVICES
! repo/com.pyamsoft.tetherfi_41.apk contains signature block blobs:
  0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Could you please clarify what those permissions are needed for? The `DEPENDENCY_INFO_BLOCK` can be easily avoided by a tiny adjustment to your `build.gradle` btw:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance for your help!

**Comment by pyamsoft** [comment]
Hey

Sorry not too sure I follow regarding the DEPENDENCY INFO BLOCK stuff

Regarding permissions

We need either the Location or Nearby permission in order to use WiFi direct APIs. Newer versions of Android do not need location and only request Nearby, old versions where Nearby does not exist request location.

Without location I am unable to use WiFi direct which powers the hotspot Access point.

Location/nearby permission is not used for anything else, except these absolutely essential WiFi direct permissions.

**Comment by IzzySoft** [comment]
> Sorry not too sure I follow regarding the DEPENDENCY INFO BLOCK stuff

I gladly help filling the gaps if you let me know what you're missing there. In our point of view, it has two issues: it's a binary blob injected that cannot be verified (so it's proprietary, essentially making the app "not fully F/LOSS") – and it can be abused to inject "PUA" (to put it friendly and not saying "malware" straight out) without breaking the signing. So it's proprietary **and** risky. Which is why I suggested to keep it out of the APK.

If you prefer, you can keep it in the AAB you upload to PlayStore, as Google *does* have the means to verify it (after all, that blob is encrypted with *their* key). In that case, simply skip the `includeInBundle` line.

> Regarding permissions

Thanks for confirming! I just needed to be sure before I add that to the app's "green list" – which I'e done now:

```yaml
    android.permission.ACCESS_FINE_LOCATION: needed on lower Android versions in order to use WiFi direct APIs
    android.permission.ACCESS_COARSE_LOCATION: needed on lower Android versions in order to use WiFi direct APIs
    android.permission.NEARBY_WIFI_DEVICES: needed on higher Android versions in order to use WiFi direct APIs
```

So this is how it will look now in the app details:

![image](https://github.com/pyamsoft/tetherfi/assets/6781438/3c080011-6ad3-433e-abfc-858f38061403)

If you want to, descriptions can be added to the other permissions as well. Just let me know then.
